<?php
declare(strict_types=1);

namespace Panth\Redirects\Test\Unit\Model\Redirect;

use Magento\Framework\App\CacheInterface;
use Magento\Store\Model\Store;
use Magento\Store\Model\StoreManagerInterface;
use Panth\Redirects\Model\Redirect\AutoRedirectService;
use Panth\Redirects\Model\Redirect\Matcher;
use Panth\Redirects\Test\Unit\DbStubTrait;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;

class AutoRedirectServiceTest extends TestCase
{
    use DbStubTrait;

    private array $cleaned = [];
    private array $logs = [];

    private function service(mixed $existing = false, array $extra = []): AutoRedirectService
    {
        $connection = $this->connectionStub(['fetchOne' => $existing] + $extra);

        $store = $this->createStub(Store::class);
        $store->method('getBaseUrl')->willReturn('https://shop.test/');
        $storeManager = $this->createStub(StoreManagerInterface::class);
        $storeManager->method('getStores')->willReturn([$store]);

        $cache = $this->createStub(CacheInterface::class);
        $cache->method('clean')->willReturnCallback(function ($tags) {
            $this->cleaned[] = $tags;
            return true;
        });

        $logger = $this->createStub(LoggerInterface::class);
        foreach (['warning', 'debug', 'info', 'error'] as $level) {
            $logger->method($level)->willReturnCallback(function ($m) use ($level) {
                $this->logs[] = [$level, (string) $m];
            });
        }

        return new AutoRedirectService($this->resourceStub($connection), $logger, $storeManager, $cache);
    }

    public function testCreatesAnAutoGeneratedLiteralRule(): void
    {
        $this->service()->createRedirect('/old-product.html', '/shoes.html', 2, 302);

        $this->assertCount(1, $this->inserts);
        $this->assertSame('pfx_panth_seo_redirect', $this->inserts[0]['table']);
        $this->assertSame([
            'pattern'           => 'old-product.html',
            'target'            => 'shoes.html',
            'status_code'       => 302,
            'match_type'        => 'literal',
            'is_active'         => 1,
            'store_id'          => 2,
            'is_auto_generated' => 1,
        ], $this->inserts[0]['data']);
        $this->assertSame([[Matcher::CACHE_TAG]], $this->cleaned);
        $this->assertSame('old-product.html', $this->whereValue('pattern = ?'));
        $this->assertSame(2, $this->whereValue('store_id = ?'));
    }

    public function testHomepageTargetKeepsItsSlash(): void
    {
        $this->service()->createRedirect('about-us', '/', 1);
        $this->assertSame('/', $this->inserts[0]['data']['target']);
    }

    public function testDuplicateSourceIsSkipped(): void
    {
        $this->service('5')->createRedirect('old', 'new', 1);

        $this->assertSame([], $this->inserts);
        $this->assertSame([], $this->cleaned);
        $this->assertSame(['debug', '[PanthRedirects] Auto-redirect skipped (duplicate)'], $this->logs[0]);
    }

    public static function noopProvider(): array
    {
        return [
            'empty source'   => ['', 'target'],
            'empty target'   => ['source', '  '],
            'same after trim' => ['/same/', 'same'],
        ];
    }

    #[DataProvider('noopProvider')]
    public function testDegenerateInputIsIgnored(string $source, string $target): void
    {
        $this->service()->createRedirect($source, $target, 1);
        $this->assertSame([], $this->inserts);
        $this->assertSame([], $this->logs);
    }

    public static function unsafeTargetProvider(): array
    {
        return [
            'javascript scheme' => ['javascript:alert(1)'],
            'file scheme'       => ['file:///etc/hosts'],
            'foreign host'      => ['https://elsewhere.test/x'],
            'parent traversal'  => ['a/../b'],
            'control character' => ["a\x01b"],
        ];
    }

    #[DataProvider('unsafeTargetProvider')]
    public function testUnsafeTargetsAreRejected(string $target): void
    {
        $this->service()->createRedirect('source', $target, 1);

        $this->assertSame([], $this->inserts);
        $this->assertSame(['warning', '[PanthRedirects] Auto-redirect rejected: unsafe target'], $this->logs[0]);
    }

    public function testAbsoluteUrlOnAStoreHostIsAllowed(): void
    {
        $this->service()->createRedirect('source', 'https://SHOP.test/new', 1);
        $this->assertSame('https://SHOP.test/new', $this->inserts[0]['data']['target']);
    }

    public function testDatabaseFailureIsLoggedAsError(): void
    {
        $this->service(false, ['insertThrows' => new \RuntimeException('locked')])
            ->createRedirect('a', 'b', 1);

        $this->assertSame(['error', '[PanthRedirects] Failed to create auto-redirect'], end($this->logs));
        $this->assertSame([], $this->cleaned);
    }
}
